# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dozent',
            options={'verbose_name': 'Dozent', 'verbose_name_plural': 'Dozenten'},
        ),
        migrations.AlterModelOptions(
            name='studiengang',
            options={'verbose_name': 'Studiengang', 'verbose_name_plural': 'Studiengänge'},
        ),
        migrations.RemoveField(
            model_name='studiengang',
            name='studienabschnitte',
        ),
        migrations.AddField(
            model_name='studiengang',
            name='studienabschnitt',
            field=models.ManyToManyField(blank=True, related_name='studiengang', to='fsmedhrocore.Studienabschnitt'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='endung',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
