# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0002_auto_20170126_1634'),
        ('fsmedhrocore', '0002_auto_20170220_1532'),
    ]

    operations = [
    ]
