# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0003_merge_20170222_1117'),
        ('fsmedhrocore', '0003_merge_20170322_1448'),
    ]

    operations = [
    ]
