# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0004_merge_20170331_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fachschaftuser',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
