# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0006_auto_20170509_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dozent',
            options={'ordering': ('nachname',), 'verbose_name': 'Dozent', 'verbose_name_plural': 'Dozenten'},
        ),
        migrations.AlterModelOptions(
            name='fach',
            options={'ordering': ('bezeichnung',), 'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
    ]
