# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='pruefer',
        ),
        migrations.AddField(
            model_name='frage',
            name='pruefer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exoral.Pruefer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='frage',
            name='testat',
        ),
        migrations.AddField(
            model_name='frage',
            name='testat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exoral.Testat'),
            preserve_default=False,
        ),
    ]
