# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoral', '0002_auto_20170126_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='antwort',
            field=models.TextField(blank=True, null=True, verbose_name='Antwort'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='datum',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Prüfungs-Datum'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='pruefer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoral.Pruefer', verbose_name='PrüferIn'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='testat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoral.Testat', verbose_name='Testat/Prüfung'),
        ),
    ]
