# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoral', '0002_auto_20170110_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbeitrag',
            name='created_date_auto',
        ),
        migrations.AddField(
            model_name='frage',
            name='datum',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 18, 31, 4, 701025)),
        ),
        migrations.AlterField(
            model_name='frage',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
