# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoral', '0003_auto_20170313_0022'),
        ('exoral', '0003_auto_20170317_1717'),
    ]

    operations = [
    ]
