# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0006_auto_20170509_0941'),
        ('exoral', '0005_merge_20170331_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testat',
            name='pruefer',
        ),
        migrations.AddField(
            model_name='testat',
            name='fach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fsmedhrocore.Fach'),
        ),
    ]
