# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhrocore', '0006_auto_20170509_0941'),
        ('exoral', '0006_auto_20170509_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testat',
            name='fach',
        ),
        migrations.AddField(
            model_name='testat',
            name='fach',
            field=models.ManyToManyField(to='fsmedhrocore.Fach'),
        ),
    ]
