# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoral', '0008_auto_20170509_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('textbeitrag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exoral.Textbeitrag')),
                ('datum', models.DateField(default=datetime.datetime.today, verbose_name='Prüfungs-Datum')),
                ('pruefer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoral.Pruefer', verbose_name='PrüferIn')),
                ('testat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoral.Testat', verbose_name='Testat/Prüfung')),
            ],
            options={
                'verbose_name_plural': 'Protokolle',
                'verbose_name': 'Protokoll',
            },
            bases=('exoral.textbeitrag',),
        ),
    ]
