# Generated by Django 2.1.8 on 2019-05-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhro_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fachschaftuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fachschaftuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
