# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 13:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Angebot',
                'ordering': ('ware__marke', 'ware__bezeichnung', 'ware__variation'),
                'verbose_name_plural': 'Angebote',
            },
        ),
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime.today, verbose_name='Auftrags-Datum')),
                ('status', models.IntegerField(choices=[(0, 'erstellt'), (1, 'bearbeitet'), (2, 'abgeschlossen')], default=0)),
            ],
            options={
                'verbose_name': 'Auftrag',
                'ordering': ('-datum', 'status'),
                'verbose_name_plural': 'Aufträge',
            },
        ),
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('oeffnungszeiten', models.TextField(blank=True, null=True, verbose_name='Öffnungszeiten')),
                ('konto_inhaber', models.CharField(default='KontoinhaberIn', max_length=30, verbose_name='KontoinhaberIn')),
                ('konto_iban', models.CharField(default='DE00000000000000000000', max_length=22, verbose_name='Konto IBAN')),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anschrift', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kundin/Kunde',
                'ordering': ('user__last_name',),
                'verbose_name_plural': 'Kundinnen/Kunden',
            },
        ),
        migrations.CreateModel(
            name='Sammelbestellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('abgeschlossen', models.BooleanField(default=False, verbose_name='abgeschlossen')),
            ],
            options={
                'verbose_name': 'Sammelbestellung',
                'ordering': ('abgeschlossen', '-ende'),
                'verbose_name_plural': 'Sammelbestellungen',
            },
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('marke', models.CharField(blank=True, max_length=30, null=True)),
                ('variation', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Ware',
                'ordering': ('marke', 'bezeichnung', 'variation'),
                'verbose_name_plural': 'Waren',
            },
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('auftrag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediathek.Auftrag')),
                ('anzahl', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sammelbestellung(Auftrag)',
                'verbose_name_plural': 'Sammelbestellungen(Aufträge)',
            },
            bases=('mediathek.auftrag',),
        ),
        migrations.AddField(
            model_name='auftrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='angebot',
            name='sammelbestellung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediathek.Sammelbestellung'),
        ),
        migrations.AddField(
            model_name='angebot',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediathek.Ware'),
        ),
        migrations.AddField(
            model_name='bestellung',
            name='angebot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediathek.Angebot'),
        ),
    ]
