# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(blank=True)),
                ('anschrift', models.CharField(blank=True, max_length=255, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('kunden_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kunden_name', models.CharField(blank=True, max_length=30, null=True)),
                ('kunden_vorname', models.CharField(blank=True, max_length=30, null=True)),
                ('kunden_email', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kundin/Kunde',
                'verbose_name_plural': 'Kundinnen/Kunden',
            },
        ),
    ]
