# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestellungPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveSmallIntegerField(default=1)),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediathek.Angebot')),
            ],
            options={
                'verbose_name_plural': 'Sammelbestellungen(Aufträge)',
                'ordering': ('angebot__ware__marke', 'angebot__ware__bezeichnung', 'angebot__ware__variation'),
                'verbose_name': 'Sammelbestellung(Auftrag)',
            },
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='angebot',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='anzahl',
        ),
        migrations.AddField(
            model_name='bestellungposition',
            name='bestellung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediathek.Bestellung'),
        ),
    ]
