# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0002_auto_20171016_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='bezahlt',
            field=models.BooleanField(default=False, verbose_name='bezahlt'),
        ),
    ]
