# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0002_auto_20170807_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sammelbestellung',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
