# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0003_sammelbestellung_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sammelbestellung',
            name='active',
        ),
        migrations.AddField(
            model_name='sammelbestellung',
            name='abgeschlossen',
            field=models.BooleanField(default=False, verbose_name='abgeschlossen'),
        ),
    ]
