# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0003_bestellung_bezahlt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='anschrift',
            field=models.TextField(blank=True, null=True),
        ),
    ]
