# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 08:51
from __future__ import unicode_literals

from django.db import migrations


def add_einstellungen(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Einstellungen = apps.get_model('mediathek', 'Einstellungen')

    inital_einstellung = Einstellungen()
    inital_einstellung.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0004_auto_20171017_1038'),
    ]

    operations = [
        migrations.RunPython(add_einstellungen),
    ]
