# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0004_auto_20171016_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('oeffnungszeiten', models.TextField(blank=True, null=True, verbose_name='Öffnungszeiten')),
                ('konto_inhaber', models.CharField(default='KontoinhaberIn', max_length=30, verbose_name='KontoinhaberIn')),
                ('konto_iban', models.CharField(default='DE00000000000000000000', max_length=22, verbose_name='Konto IBAN')),
            ],
            options={
                'verbose_name_plural': 'Einstellungen',
                'verbose_name': 'Einstellungen',
            },
        ),
    ]
