# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0005_einstellungen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angebot',
            options={'ordering': ('ware__marke', 'ware__bezeichnung', 'ware__variation'), 'verbose_name': 'Angebot', 'verbose_name_plural': 'Angebote'},
        ),
        migrations.AlterModelOptions(
            name='kunde',
            options={'ordering': ('user__last_name',), 'verbose_name': 'Kundin/Kunde', 'verbose_name_plural': 'Kundinnen/Kunden'},
        ),
        migrations.AlterModelOptions(
            name='sammelbestellung',
            options={'ordering': ('abgeschlossen', 'ende'), 'verbose_name': 'Sammelbestellung', 'verbose_name_plural': 'Sammelbestellungen'},
        ),
        migrations.AlterModelOptions(
            name='ware',
            options={'ordering': ('marke', 'bezeichnung', 'variation'), 'verbose_name': 'Ware', 'verbose_name_plural': 'Waren'},
        ),
    ]
