# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0005_auto_20171031_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestellungposition',
            options={'ordering': ('angebot__ware__marke', 'angebot__ware__bezeichnung', 'angebot__ware__variation'), 'verbose_name': 'Bestellungs-Position', 'verbose_name_plural': 'Bestellungs-Positionen'},
        ),
    ]
