# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0006_auto_20171031_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='bezeichnung',
            field=models.CharField(max_length=40),
        ),
    ]
