# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediathek', '0006_auto_20171016_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sammelbestellung',
            options={'ordering': ('abgeschlossen', '-ende'), 'verbose_name': 'Sammelbestellung', 'verbose_name_plural': 'Sammelbestellungen'},
        ),
    ]
