# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediathek', '0007_auto_20171016_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auftrag',
            options={'ordering': ('-datum', 'status'), 'verbose_name': 'Auftrag', 'verbose_name_plural': 'Aufträge'},
        ),
        migrations.RemoveField(
            model_name='auftrag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auftrag',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='auftrag',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='auftrag',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='auftrag',
            name='version',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='version',
        ),
        migrations.AddField(
            model_name='auftrag',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
