# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsmedhrocore', '0003_merge_20170222_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Studienabschnitt', models.ManyToManyField(to='fsmedhrocore.Studienabschnitt')),
                ('Studiengang', models.ManyToManyField(to='fsmedhrocore.Studiengang')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('datum', models.DateField(default=datetime.datetime.today, verbose_name='Klausurdatum')),
                ('Fach', models.ManyToManyField(to='QuestionAir.Fach')),
            ],
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(blank=True)),
                ('text', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionAir.Frage')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='QuestionAirUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='frage',
            name='Klausur',
            field=models.ManyToManyField(to='QuestionAir.Klausur'),
        ),
        migrations.AddField(
            model_name='frage',
            name='submitter',
            field=models.ManyToManyField(to='QuestionAir.QuestionAirUser'),
        ),
    ]
