# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausur',
            options={'verbose_name': 'Klausur', 'verbose_name_plural': 'Klausuren'},
        ),
    ]
