# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAir', '0003_auto_20170320_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='submitter',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
